name: Continuous Integration

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_DISCORD_DUNGEON_BASE_URL: "https://discorddungeon.com"

    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          dry: true
          prettier_version: 2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "21"
          cache: npm
          cache-dependency-path: |
            package-lock.json
      - name: Install npm 
        run: npm install -g npm@10.2.3
      - name: install UI Dependencies
        run: npm ci
      - name: Build the ui
        run: npm run build -- --watch false